version: '3.8'

services:
  db:
    image: postgres:13
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_DB: chat_users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build:
      context: .
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: chat_users
    depends_on:
      - db
volumes:
  pgdata:
